// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG6AFPBU1vi31sIdaJyqNwiImSiLozUio',
    appId: '1:86243436179:web:2ed5d551a19d4ef8a20f66',
    messagingSenderId: '86243436179',
    projectId: 'edu-mart-d9550',
    authDomain: 'edu-mart-d9550.firebaseapp.com',
    storageBucket: 'edu-mart-d9550.firebasestorage.app',
    measurementId: 'G-GL8XB5XDW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI04jDvp2Z42Dv6ZB7ECl_8Rb2qse7wgY',
    appId: '1:86243436179:android:09ad7f5ab31f2296a20f66',
    messagingSenderId: '86243436179',
    projectId: 'edu-mart-d9550',
    storageBucket: 'edu-mart-d9550.firebasestorage.app',
  );
}
